(defun load-user-file (file)
  (interactive "f")
  "Load a file in current user's configuration directory"
  (load-file (expand-file-name file user-emacs-directory)))

(load-user-file "packages.el")
(load-user-file "ui.el")
(load-user-file "ibuffer.el")
(load-user-file "commands.el")
(load-user-file "haskell.el")
(load-user-file "cpp.el")
(load-user-file "html.el")
(load-user-file "gdb.el")
(load-user-file "w3m.el")
(load-user-file "newsticker.el")
